# Generated by Django 3.0.3 on 2020-02-24 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='contact',
            field=models.CharField(default='', help_text=' your registerd phone number with university if availabe ,your number help us to auto verify your profile', max_length=10, validators=[django.core.validators.RegexValidator(message='10 digits only ', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.CharField(choices=[('ND', '---'), ('CE', 'Civil Eng.'), ('CS', 'Computer Science Eng.'), ('EC', 'Electronics & Commu.'), ('EEE', 'Electrical and Electronics Eng.'), ('IT', 'Information Tech.'), ('ME', 'Mechanical Eng.'), ('MCA', 'Master of Computer App.')], max_length=3),
        ),
    ]
