# Generated by Django 3.0.3 on 2020-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.CharField(choices=[('CE', 'Civil Eng.'), ('CS', 'Computer Science Eng.'), ('EC', 'Electronics & Commu.'), ('EEE', 'Electrical and Electronics Eng.'), ('IT', 'Information Tech.'), ('ME', 'Mechanical Eng.'), ('MCA', 'Master of Computer App.')], max_length=3),
        ),
    ]
