# Generated by Django 3.0.3 on 2020-02-28 06:53

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200225_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Alumni')),
                ('profile_pic', models.ImageField(default='profile.png', help_text='Profile Picture', upload_to=account.models.user_directory_path)),
                ('bio', models.TextField(blank=True, default='ND', max_length=500)),
                ('work', models.CharField(blank=True, default='Student', help_text='eg:- Web Developer ,s/w Architect, s/m admin...etc', max_length=30)),
                ('organization', models.CharField(blank=True, default='ND', max_length=100)),
                ('linkedin', models.URLField(blank=True, default='https://www.linkedin.com/in/username/')),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/username')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/username')),
                ('private', models.BooleanField(default=False, help_text='<b>Make Your Profile Private</b>')),
            ],
        ),
    ]
