# Generated by Django 3.0.3 on 2020-05-21 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alumniprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecompletion',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='start',
            field=models.DateField(blank=True),
        ),
    ]
