# Generated by Django 3.0.3 on 2020-06-23 13:35

import account.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200620_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuelVerification',
            fields=[
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Alumni')),
                ('verify_status', models.CharField(choices=[('PD', 'PENDING'), ('ND', 'NOT VALID'), ('VD', 'VERIFIED')], max_length=2)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Manuel Verifications',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='alumni',
            name='verification_file',
            field=models.ImageField(default='File.png', help_text='Verification ID', upload_to=account.models.file_directory_path),
        ),
    ]
