# Generated by Django 3.0.3 on 2020-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200623_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='skills',
            field=models.CharField(blank=True, default='Analytical Skill', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='organization',
            field=models.CharField(blank=True, default='XYZ Co', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='private',
            field=models.BooleanField(default=True, help_text='<b>Make Your Profile Private</b>'),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='work',
            field=models.CharField(blank=True, default='Developer', help_text='eg:- Web Developer ,s/w Architect, s/m admin...etc', max_length=30),
        ),
    ]
