# Generated by Django 3.0.3 on 2020-06-25 08:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20200624_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateField(blank=True)),
                ('req_skills', models.CharField(blank=True, max_length=100, null=True)),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='ND', max_length=500)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time')], default='FT', max_length=3)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('workexp_req', models.CharField(blank=True, max_length=1000, null=True)),
                ('base_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('questions_to_applicants', models.TextField(blank=True, max_length=1000, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_author', to='account.Alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(upload_to=jobs.models.user_resume_path)),
                ('contact', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='10 digits only ', regex='^[0-9]{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('answers_to_employer', models.TextField(blank=True, default='ND', max_length=500)),
                ('questions_to_employer', models.TextField(blank=True, default='ND', max_length=500)),
                ('answers_to_applicants', models.TextField(blank=True, default='ND', max_length=500)),
                ('application_status', models.CharField(choices=[('APP', 'Approved'), ('PED', 'Pending')], default='PED', max_length=3)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applicant', to=settings.AUTH_USER_MODEL)),
                ('applying_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_job', to='jobs.Job')),
            ],
        ),
    ]
