# Generated by Django 3.0.3 on 2020-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiserevent',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fundraiserevent',
            name='raised_amount',
            field=models.IntegerField(default=0),
        ),
    ]
