# Generated by Django 3.0.3 on 2020-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0002_auto_20200527_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiserevent',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
