# Generated by Django 3.0.3 on 2020-05-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0004_auto_20200527_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_event', to='fundraiser.FundRaiserEvent'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txn_status',
            field=models.CharField(choices=[('init', 'Initiated'), ('success', 'Success.'), ('failed', 'Failed'), ('refunded', 'Refund')], default='init', max_length=8),
        ),
    ]
