# Generated by Django 3.0.3 on 2020-02-24 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(default='', help_text=' your registerd phone number with university if availabe ,your number help us to auto verify your profile', max_length=10, validators=[django.core.validators.RegexValidator(message='10 digits only ', regex='^[0-9]{10}$')])),
                ('batch', models.CharField(default='', max_length=9, validators=[django.core.validators.RegexValidator(message='10 digits only ', regex='^[0-9]{10}$')])),
            ],
        ),
    ]
