# Generated by Django 3.0.3 on 2020-05-22 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(help_text='mail@cucek.in', max_length=254, unique=True)),
                ('contact', models.CharField(help_text='eg:9876543210', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='10 digits only ', regex='^[0-9]{10}$')])),
                ('batch', models.CharField(default='', help_text='eg:2017-2021', max_length=9, validators=[django.core.validators.RegexValidator(message='Should follow the format eg: 2017-2021 ', regex='^\\d{4}-\\d{4}$')])),
            ],
        ),
    ]
