# Generated by Django 3.0.3 on 2020-02-24 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidb',
            name='batch',
            field=models.CharField(default='', help_text='eg:2017-2021', max_length=9, validators=[django.core.validators.RegexValidator(message='Should follow the format eg: 2017-2021 ', regex='^\\d{4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='alumnidb',
            name='contact',
            field=models.CharField(default='', help_text='eg:9876543210', max_length=10, validators=[django.core.validators.RegexValidator(message='10 digits only ', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='alumnidb',
            name='email',
            field=models.EmailField(help_text='mail@cucek.in', max_length=254, unique=True),
        ),
    ]
