# Generated by Django 3.0.3 on 2020-02-24 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0002_auto_20200225_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidb',
            name='contact',
            field=models.CharField(help_text='eg:9876543210', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='10 digits only ', regex='^[0-9]{10}$')]),
        ),
    ]
